// TestEngineAPI.cs : Declares the DLL functions for C#.
// Generated by E:\Jenkins\workspace\BlueSuite_v3_X_Y_RCZ\common\hosttools\crs_tools_bs3\prodtest\scripts\extract_tt_api.pl from TestEngine.h;  at 11/06/18 - 11:04:15
// Copyright (c) 2004-2018 Qualcomm Technologies International, Ltd.
// All Rights Reserved.
// Qualcomm Technologies International, Ltd. Confidential and Proprietary.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace TestEngineAPI
{
    public class TestEngine
    {
#if PocketPC || WindowsCE
        const CharSet charset = CharSet.Auto;
        const CallingConvention calling_convention = CallingConvention.Winapi;
#else
        const CharSet charset = CharSet.Ansi;
        const CallingConvention calling_convention = CallingConvention.StdCall;
#endif

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetVersion",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetVersion(StringBuilder versionStr);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetVersion",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetVersion(byte [] versionStr);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngine",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngine(int transport, String transportDevice, uint dataRate, int retryTimeOut, int usbTimeOut);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngine",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngine(int transport, byte [] transportDevice, uint dataRate, int retryTimeOut, int usbTimeOut);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineUnlock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineUnlock(int transport, String transportDevice, int retryTimeOut, int usbTimeOut, String unlockKey);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineUnlock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineUnlock(int transport, byte [] transportDevice, int retryTimeOut, int usbTimeOut, byte [] unlockKey);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpi",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpi(int port, int multi, int transport);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiUnlock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiUnlock(int port, int multi, int transport, String unlockKey);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiUnlock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiUnlock(int port, int multi, int transport, byte [] unlockKey);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiTrans",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiTrans(String trans, int multi);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiTrans",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiTrans(byte [] trans, int multi);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiUnlockTrans",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiUnlockTrans(String trans, int multi, String unlockKey);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="openTestEngineSpiUnlockTrans",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint openTestEngineSpiUnlockTrans(byte [] trans, int multi, byte [] unlockKey);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="closeTestEngine",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int closeTestEngine(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetLastError",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern uint teGetLastError(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetColdReset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetColdReset(uint handle, int usbTimeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetWarmReset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetWarmReset(uint handle, int usbTimeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPause",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPause(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestDeepSleep",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestDeepSleep(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmExtLb",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmExtLb(uint handle, ushort pcmMode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmExtLbIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmExtLbIf(uint handle, ushort pcmMode, ushort pcmIf);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmLb",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmLb(uint handle, ushort pcmMode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmLbIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmLbIf(uint handle, ushort pcmMode, ushort pcmIf);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmTimingIn",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmTimingIn(uint handle, ushort pioOut, ushort pcmIn);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmTimingInIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmTimingInIf(uint handle, ushort pioOut, ushort pcmIn, ushort pcmIf);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmTone",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmTone(uint handle, ushort freq, ushort ampl, ushort dc);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmToneIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmToneIf(uint handle, ushort freq, ushort ampl, ushort dc, ushort pcmIf);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestPcmToneStereo",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestPcmToneStereo(uint handle, ushort freq, ushort ampl, ushort dc, ushort channel);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCtsRtsLb",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCtsRtsLb(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRadioStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRadioStatus(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetRadioStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetRadioStatus(uint handle, ushort [] status, int timeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRadioStatusArray",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRadioStatusArray(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetRadioStatusArray",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetRadioStatusArray(uint handle, ushort [] status, int timeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdMemoryGet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdMemoryGet(uint handle, ushort baseAddr, ushort dataLength, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdMemorySet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdMemorySet(uint handle, ushort baseAddr, ushort dataLength, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetBuildId",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetBuildId(uint handle, out ushort buildId);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBuildName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBuildName(uint handle, StringBuilder name, ushort maxLen, out ushort length);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBuildName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBuildName(uint handle, byte [] name, ushort maxLen, out ushort length);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetChipVersion",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetChipVersion(uint handle, out ushort chipVer);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetChipRevision",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetChipRevision(uint handle, out ushort chipRev);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetChipAnaVer",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetChipAnaVer(uint handle, out byte major, out byte minor, out byte vari);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdRouteClock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdRouteClock(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdRssiAcl",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdRssiAcl(uint handle, ushort connectionHandle, out short rssi);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetPio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetPio(uint handle, ushort mask, ushort port);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetPio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetPio(uint handle, out ushort mask, out ushort port);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdMapPio32",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdMapPio32(uint handle, uint mask, uint pios, out uint errLines);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetPio32",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetPio32(uint handle, uint mask, uint direction, uint value, out uint errLines);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetPio32",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetPio32(uint handle, out uint direction, out uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetAdc",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetAdc(uint handle, ushort adc, out ushort result);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetAio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetAio(uint handle, ushort aio, out ushort result, out byte numBits);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBC5MMGetBatteryVoltage",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBC5MMGetBatteryVoltage(uint handle, out ushort voltage);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetFirmwareCheckMask",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetFirmwareCheckMask(uint handle, out ushort mask);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetFirmwareCheck",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetFirmwareCheck(uint handle, out ushort check);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetExternalClockPeriod",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetExternalClockPeriod(uint handle, out ushort period);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdEnableDeviceConnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdEnableDeviceConnect(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdEnableDeviceUnderTestMode",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdEnableDeviceUnderTestMode(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdCheckSqifImageValidationStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdCheckSqifImageValidationStatus(uint handle, out ushort status, ushort timeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestStereoCodecLB",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestStereoCodecLB(uint handle, ushort sampleRate, ushort reroute);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestTxstart",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestTxstart(uint handle, ushort frequency, ushort power1, ushort power2, short modulation);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestTxdata1",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestTxdata1(uint handle, ushort frequency, ushort power1, ushort power2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestTxdata2",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestTxdata2(uint handle, ushort countryCode, ushort power1, ushort power2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestTxdata3",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestTxdata3(uint handle, ushort frequency, ushort power1, ushort power2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestTxdata4",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestTxdata4(uint handle, ushort frequency, ushort power1, ushort power2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgTxPower",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgTxPower(uint handle, short power);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRxstart1",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRxstart1(uint handle, ushort frequency, byte hiSide, ushort rxAttenuation);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRxstart2",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRxstart2(uint handle, ushort frequency, byte hiSide, ushort rxAttenuation, ushort sampleSize);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetRssi",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetRssi(uint handle, int timeout, ushort maxSize, ushort [] rssiSamples);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestBer1",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestBer1(uint handle, ushort frequency, byte hiSide, ushort rxAttenuation, uint sampleSize);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestBer2",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestBer2(uint handle, ushort countryCode, byte hiSide, ushort rxAttenuation, uint sampleSize);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestBerLoopback",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestBerLoopback(uint handle, ushort frequency, ushort power1, ushort power2, uint sampleSize);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRxLoopback",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRxLoopback(uint handle, ushort frequency, ushort intPA, ushort extPA);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestLoopback",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestLoopback(uint handle, ushort frequency, ushort power1, ushort power2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetBer",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetBer(uint handle, int timeout, uint [] berReport);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRxdata1",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRxdata1(uint handle, ushort frequency, byte hiSide, ushort rxAttenuation);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestRxdata2",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestRxdata2(uint handle, ushort countryCode, byte hiSide, ushort rxAttenuation);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetRxdata",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetRxdata(uint handle, int timeout, ushort [] rxData);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgFreq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgFreq(uint handle, ushort txRxInterval, ushort loopback, ushort report);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgFreqMs",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgFreqMs(uint handle, ushort txRxInterval, ushort loopback, ushort report);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgPkt",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgPkt(uint handle, ushort aType, ushort size);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgBitError",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgBitError(uint handle, uint sampleSize, byte reset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgTxPaAtten",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgTxPaAtten(uint handle, ushort atten);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgXtalFtrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgXtalFtrim(uint handle, ushort fTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCalcXtalOffset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCalcXtalOffset(double nominalFreqMhz, double actualFreqMhz, out short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgUapLap",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgUapLap(uint handle, ushort uap, uint lap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgIqTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgIqTrim(uint handle, ushort trim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgTxIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgTxIf(uint handle, short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgTxTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgTxTrim(uint handle, ushort amAddr);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgLoLvl",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgLoLvl(uint handle, ushort loLvl);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestCfgHoppingSeq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestCfgHoppingSeq(uint handle, ushort [] channels);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestSettle",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestSettle(uint handle, ushort start, ushort aEnd);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetSettle",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetSettle(uint handle, ushort [] results);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="get_freq_offset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int get_freq_offset(uint handle, out double offset, int sampleSize);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetEeprom",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetEeprom(uint handle, ushort log2bytes, ushort addrMask);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadBdAddr",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadBdAddr(uint handle, out uint lap, out byte uap, out ushort nap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psRead(uint handle, ushort psKey, ushort store, ushort arrayLen, ushort [] data, out ushort aLen);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psClear",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psClear(uint handle, ushort psKey, ushort store);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psClearAll",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psClearAll(uint handle, ushort store);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psFactorySet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psFactorySet(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psFactoryRestoreAll",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psFactoryRestoreAll(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psFactoryRestore",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psFactoryRestore(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psSize",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psSize(uint handle, ushort psKey, ushort store, out ushort size);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWrite(uint handle, ushort psKey, ushort store, ushort length, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteVerify",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteVerify(uint handle, ushort psKey, ushort store, ushort length, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteBdAddr",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteBdAddr(uint handle, uint lap, uint uap, uint nap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadModuleId",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadModuleId(uint handle, out uint moduleId);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadXtalFtrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadXtalFtrim(uint handle, out ushort fTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteXtalFtrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteXtalFtrim(uint handle, ushort fTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadXtalOffset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadXtalOffset(uint handle, out short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteXtalOffset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteXtalOffset(uint handle, short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteModuleSecurityCode",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteModuleSecurityCode(uint handle, ushort [] code);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteModuleId",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteModuleId(uint handle, uint moduleId);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteBaudrate",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteBaudrate(uint handle, ushort value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteRadiotestFirstTrimTime",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteRadiotestFirstTrimTime(uint handle, uint time);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadRadiotestFirstTrimTime",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadRadiotestFirstTrimTime(uint handle, out uint time);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteRadiotestLoLvlTrimEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteRadiotestLoLvlTrimEnable(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadRadiotestLoLvlTrimEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadRadiotestLoLvlTrimEnable(uint handle, out ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteRadiotestSubsequentTrimTime",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteRadiotestSubsequentTrimTime(uint handle, uint time);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadRadiotestSubsequentTrimTime",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadRadiotestSubsequentTrimTime(uint handle, out uint time);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteHostInterface",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteHostInterface(uint handle, ushort transport);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadHostInterface",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadHostInterface(uint handle, out ushort transport);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteUsbAttributes",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteUsbAttributes(uint handle, ushort bmAttributes);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteDPlusPullup",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteDPlusPullup(uint handle, ushort pioPin);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteUsbMaxPower",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteUsbMaxPower(uint handle, ushort maxPower);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWritePioProtectMask",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWritePioProtectMask(uint handle, ushort mask);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadPioProtectMask",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadPioProtectMask(uint handle, out ushort mask);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteTxOffsetHalfMhz",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteTxOffsetHalfMhz(uint handle, short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadTxOffsetHalfMhz",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadTxOffsetHalfMhz(uint handle, out short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteUsrValue",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteUsrValue(uint handle, ushort userNo, ushort length, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadUsrValue",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadUsrValue(uint handle, ushort userNo, ushort maxLen, out ushort length, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWritePowerTable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWritePowerTable(uint handle, ushort numEntries, byte intPA, byte [] extPA, int [] power);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadPowerTable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadPowerTable(uint handle, int maxSize, out int numEntries, byte [] intPA, byte [] extPA, int [] power);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psWriteVmDisable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psWriteVmDisable(uint handle, byte vmDisable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psReadVmDisable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psReadVmDisable(uint handle, out byte vmDisable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psMergeFromFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psMergeFromFile(uint handle, String filePath);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="psMergeFromFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int psMergeFromFile(uint handle, byte [] filePath);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSlave",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSlave(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSetAfhHostChannelClass",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSetAfhHostChannelClass(uint handle, byte [] cClass);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReadAfhChannelMap",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReadAfhChannelMap(uint handle, ushort aclHandle, out byte mode, byte [] cMap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSetEventFilterAutoacceptConnection",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSetEventFilterAutoacceptConnection(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWriteInquiryScanActivity",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWriteInquiryScanActivity(uint handle, ushort interval, ushort window);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWritePageScanActivity",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWritePageScanActivity(uint handle, ushort interval, ushort window);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWriteScanEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWriteScanEnable(uint handle, byte scanEnable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciInquiry",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciInquiry(uint handle, byte inquiryLength, byte numResponses, uint lap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetInquiryResults",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetInquiryResults(uint handle, uint [] lap, byte [] uap, ushort [] nap, ushort [] clockOffset, uint maxLen, out uint aLen);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciInquiryCancel",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciInquiryCancel(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciCreateConnection",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciCreateConnection(uint handle, uint lap, byte uap, ushort nap, ushort pktType, out ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciCreateConnectionNoInquiry",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciCreateConnectionNoInquiry(uint handle, uint lap, byte uap, ushort nap, ushort pktType, byte pageScanRepMode, byte pageScanMode, ushort clockOffset, byte allowRoleSwitch, out ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciCreateScoConnection",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciCreateScoConnection(uint handle, ushort aclConnectionHandle, ushort pktType, out ushort scoConnectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSetupScoConnection",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSetupScoConnection(uint handle, ushort aclConnectionHandle, uint txBandwidth, uint rxBandwidth, ushort maxLatency, ushort voiceSetting, byte retransEffort, ushort pktType, out ushort scoConnectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReadVoiceSetting",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReadVoiceSetting(uint handle, out ushort voiceSetting);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWriteVoiceSetting",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWriteVoiceSetting(uint handle, ushort voiceSetting);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWriteLinkPolicySettings",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWriteLinkPolicySettings(uint handle, ushort connectionHandle, ushort linkPolicySettings);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSendAclFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSendAclFile(uint handle, ushort connHandle, String fileName);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSendAclFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSendAclFile(uint handle, ushort connHandle, byte [] fileName);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSendAclData",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSendAclData(uint handle, ushort connHandle, byte [] data, ushort length);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetAclData",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetAclData(uint handle, byte [] data, out uint numBytes);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetAclBytesRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetAclBytesRead(uint handle, out uint numBytes);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetAclFileName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetAclFileName(uint handle, StringBuilder fileName, out uint length);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetAclFileName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetAclFileName(uint handle, byte [] fileName, out uint length);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetAclState",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetAclState(uint handle, out int state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciResetAclState",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciResetAclState(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReset(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetAnaXtalFtrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetAnaXtalFtrim(uint handle, out ushort fTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetAnaXtalFtrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetAnaXtalFtrim(uint handle, ushort fTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSniffMode",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSniffMode(uint handle, ushort connectionHandle, ushort sniffMaxInterval, ushort sniffMinInterval, ushort sniffAttempt, ushort sniffTimeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciExitSniff",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciExitSniff(uint handle, ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciDisconnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciDisconnect(uint handle, ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetConnectionHandle",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetConnectionHandle(uint handle, uint lap, byte uap, ushort nap, out ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciConnectionStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciConnectionStatus(uint handle, ushort connectionHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciEnableDeviceUnderTestMode",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciEnableDeviceUnderTestMode(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciGetLinkQuality",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciGetLinkQuality(uint handle, ushort connectionHandle, out byte quality);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReadRemoteVersionInformation",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReadRemoteVersionInformation(uint handle, ushort connectionHandle, uint [] versionInfo);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReadRemoteNameRequest",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReadRemoteNameRequest(uint handle, uint lap, byte uap, ushort nap, byte pageScanRepMode, byte pageScanOffset, ushort clockOffset, StringBuilder remoteName);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciReadRemoteNameRequest",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciReadRemoteNameRequest(uint handle, uint lap, byte uap, ushort nap, byte pageScanRepMode, byte pageScanOffset, ushort clockOffset, byte [] remoteName);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmRegisterReq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmRegisterReq(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmSlave",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmSlave(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmEnableDeviceUnderTestMode",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmEnableDeviceUnderTestMode(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmWritePageScanActivity",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmWritePageScanActivity(uint handle, ushort interval, ushort window);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmWriteInquiryScanActivity",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmWriteInquiryScanActivity(uint handle, ushort interval, ushort window);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmWriteScanEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmWriteScanEnable(uint handle, byte scanEnable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="dmSetEventFilterAutoacceptConnection",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int dmSetEventFilterAutoacceptConnection(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBc3PsuTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBc3PsuTrim(uint handle, ushort data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdChargerPsuTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdChargerPsuTrim(uint handle, ushort trim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBc3BuckReg",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBc3BuckReg(uint handle, ushort data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdPsuSmpsEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdPsuSmpsEnable(uint handle, ushort reg);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBc3MicEn",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBc3MicEn(uint handle, ushort data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdPsuHvLinearEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdPsuHvLinearEnable(uint handle, ushort reg);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBc3Led0",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBc3Led0(uint handle, ushort data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdLedEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdLedEnable(uint handle, ushort led, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdLed0Enable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdLed0Enable(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBc3Led1",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBc3Led1(uint handle, ushort data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdLed1Enable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdLed1Enable(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdChargerStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdChargerStatus(uint handle, out ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdChargerDisable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdChargerDisable(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdChargerSuppressLed0",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdChargerSuppressLed0(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciCreateConnectionNoWait",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciCreateConnectionNoWait(uint handle, uint lap, byte uap, ushort nap, ushort pktType, byte pageScanRepMode, byte pageScanMode, ushort clockOffset, byte allowRoleSwitch);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWriteAuthenticationEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWriteAuthenticationEnable(uint handle, byte enable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciLinkKeyRequestNegativeReply",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciLinkKeyRequestNegativeReply(uint handle, uint lap, byte uap, ushort nap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWaitForConnectionComplete",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWaitForConnectionComplete(uint handle, out ushort connHandle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWaitForLinkKeyRequest",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWaitForLinkKeyRequest(uint handle, out uint lap, out byte uap, out ushort nap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWaitForPinCodeRequest",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWaitForPinCodeRequest(uint handle, out uint lap, out byte uap, out ushort nap);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciWaitForEncryptionChange",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciWaitForEncryptionChange(uint handle, out byte enable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciPinCodeRequestReply",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciPinCodeRequestReply(uint handle, uint lap, byte uap, ushort nap, byte pinCodeLength, byte [] pinCode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hciSetConnectionEncryption",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hciSetConnectionEncryption(uint handle, ushort connHandle, byte enable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="vmWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int vmWrite(uint handle, ushort [] data);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="vmRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int vmRead(uint handle, ushort [] data, ushort timeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetSingleChan",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetSingleChan(uint handle, ushort channel);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetHoppingOn",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetHoppingOn(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmSwitchPower",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmSwitchPower(uint handle, byte powerOn);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmSetFreq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmSetFreq(uint handle, uint freqKHz);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmGetRssi",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmGetRssi(uint handle, out sbyte rssi);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmGetSnr",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmGetSnr(uint handle, out short snr);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmGetIfOffset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmGetIfOffset(uint handle, out short offset);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmGetStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmGetStatus(uint handle, out byte status);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmSetupAudio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmSetupAudio(uint handle, byte route, byte gain, byte channel);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmVerifyRDSPi",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmVerifyRDSPi(uint handle, ushort pi, ushort timeoutMs, out byte matched);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmTxSwitchPower",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmTxSwitchPower(uint handle, byte powerOn);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmTxSetFreq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmTxSetFreq(uint handle, uint freqKHz);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmTxSetPowerLevel",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmTxSetPowerLevel(uint handle, short powerLevel);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdFmTxSetupAudio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdFmTxSetupAudio(uint handle, byte route, ushort audioGain);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdDisconnectAudio",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdDisconnectAudio(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdAudioGetSource",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdAudioGetSource(uint handle, ushort device, ushort iface, ushort channel, out ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdAudioGetSink",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdAudioGetSink(uint handle, ushort device, ushort iface, ushort channel, out ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdAudioConfigure",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdAudioConfigure(uint handle, ushort sid, ushort key, uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdDirectChargerPsuTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdDirectChargerPsuTrim(uint handle, ushort trim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teSupportsHq",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teSupportsHq(uint handle, out byte hqSupported);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetAuxDac",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetAuxDac(uint handle, byte enable, byte level);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetMicBiasIf",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetMicBiasIf(uint handle, byte instance, byte enable, byte voltage);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetMicBias",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetMicBias(uint handle, byte enable, byte voltage, byte current, byte enableLowPowerMode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetAvailableSpiPorts",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetAvailableSpiPorts(out ushort maxLen, StringBuilder ports, StringBuilder trans, out ushort count);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetAvailableSpiPorts",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetAvailableSpiPorts(out ushort maxLen, byte [] ports, byte [] trans, out ushort count);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdProvokeFault",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdProvokeFault(uint handle, ushort faultCode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetFaultReports",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetFaultReports(uint handle, ushort maxReports, ushort [] codes, uint [] timestamps, ushort [] repeats, out ushort numReports, int timeout);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetFaultDesc",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetFaultDesc(uint handle, ushort faultCode, StringBuilder desc);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetFaultDesc",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetFaultDesc(uint handle, ushort faultCode, byte [] desc);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetMapScoPcm",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetMapScoPcm(uint handle, byte enable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetVrefConstant",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetVrefConstant(uint handle, out ushort vref);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetVrefAdc",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetVrefAdc(uint handle, out ushort result, out byte numBits);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdBC5FMGetI2CState",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdBC5FMGetI2CState(uint handle, out byte sda, out byte scl);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpGetRssiDbm",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpGetRssiDbm(uint handle, ushort freqMHz, double rssiChip, out double rssiDbm);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpGetPaLevel",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpGetPaLevel(uint handle, ushort freqMHz, double targetPowerDbm, out ushort intPa, out double powerDbm);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpWriteCalDataFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpWriteCalDataFile(uint handle, String filePath);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpWriteCalDataFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpWriteCalDataFile(uint handle, byte [] filePath);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpLoadCalDataFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpLoadCalDataFile(uint handle, String filePath);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="refEpLoadCalDataFile",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int refEpLoadCalDataFile(uint handle, byte [] filePath);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetVmStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetVmStatus(uint handle, out ushort status, out ushort exitCode);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdI2CTransfer",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdI2CTransfer(uint handle, ushort slaveAddr, ushort txOctets, ushort rxOctets, byte restart, byte [] data, out ushort octets);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="radiotestBle",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int radiotestBle(uint handle, ushort command, byte channel, byte txLength, byte txPayload);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="hqGetBleRxPktCount",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hqGetBleRxPktCount(uint handle, int timeout, out ushort pktCount);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetChargerTrims",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetChargerTrims(uint handle, out ushort chgRefTrim, out ushort hVrefTrim, out ushort rTrim, out ushort iTrim, out ushort iExtTrim, out ushort iTermTrim, out ushort vFastTrim, out ushort hystTrim);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdCapacitiveSensorRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdCapacitiveSensorRead(uint handle, ushort mask, ushort [] values);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSetSpiLockCustomerKey",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSetSpiLockCustomerKey(uint handle, uint [] custKey);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdGetSpiLockStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdGetSpiLockStatus(uint handle, out ushort status);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdSpiLockInitiateLock",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdSpiLockInitiateLock(uint handle);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetChipDisplayName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetChipDisplayName(uint handle, uint maxLen, StringBuilder name);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetChipDisplayName",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetChipDisplayName(uint handle, uint maxLen, byte [] name);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetChipFamily",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetChipFamily(uint handle, out byte family);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetPtapHifs",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetPtapHifs(out ushort length, StringBuilder hifIds, StringBuilder types, StringBuilder names, out ushort count);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetPtapHifs",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetPtapHifs(out ushort length, byte [] hifIds, byte [] types, byte [] names, out ushort count);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teMcSetXtalFreqTrim",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teMcSetXtalFreqTrim(uint handle, ushort trimVal, out short mibVal);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teMcSetXtalLoadCapacitance",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teMcSetXtalLoadCapacitance(uint handle, ushort value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teGetBuildId",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teGetBuildId(uint handle, byte subsystem, out uint buildId);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePioMap",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePioMap(uint handle, ushort bank, uint mask, uint pios, out uint errLines);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePioSet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePioSet(uint handle, ushort bank, uint mask, uint direction, uint value, out uint errLines);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePioGet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePioGet(uint handle, ushort bank, out uint direction, out uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioGetSource",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioGetSource(uint handle, ushort device, ushort iface, ushort channel, out ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioCloseSource",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioCloseSource(uint handle, ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioGetSink",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioGetSink(uint handle, ushort device, ushort iface, ushort channel, out ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioCloseSink",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioCloseSink(uint handle, ushort sid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioConnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioConnect(uint handle, ushort sourceId, ushort sinkId, out ushort tid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioDisconnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioDisconnect(uint handle, ushort tid);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioConfigure",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioConfigure(uint handle, ushort sid, ushort key, uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioCreateOperator",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioCreateOperator(uint handle, ushort capabilityId, out ushort operatorId);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioDestroyOperators",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioDestroyOperators(uint handle, ushort [] operators, ushort count);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioOperatorMessage",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioOperatorMessage(uint handle, ushort operatorId, ushort [] message, ushort messageLength);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioStartOperators",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioStartOperators(uint handle, ushort [] operators, ushort count);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioStopOperators",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioStopOperators(uint handle, ushort [] operators, ushort count);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioSetAncIirFilter",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioSetAncIirFilter(uint handle, ushort ancInstance, ushort pathId, ushort [] coefficients, ushort numCoeffs);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioSetAncLpfFilter",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioSetAncLpfFilter(uint handle, ushort ancInstance, ushort pathId, ushort shift1, ushort shift2);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioStreamAncEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioStreamAncEnable(uint handle, ushort anc0, ushort anc1);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAudioMicBiasConfigure",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAudioMicBiasConfigure(uint handle, ushort id, ushort key, uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teCapacitiveSensorRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teCapacitiveSensorRead(uint handle, ushort pad, out uint value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teCheckLicense",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teCheckLicense(uint handle, byte featureId, out byte result);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teCheckLicenses",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teCheckLicenses(uint handle, ushort numFeatureIds, ushort [] featureIds, byte [] results);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAppDisable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAppDisable(uint handle, ushort reserved);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAppWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAppWrite(uint handle, byte channel, ushort [] data, ushort length);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAppRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAppRead(uint handle, out byte channel, ushort [] data, ushort dataLength, out ushort readLength, ushort timeoutMs);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teAdcGet",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teAdcGet(uint handle, ushort adc, ushort delay, ushort reserved, out ushort result);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teChargerSetConfig",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teChargerSetConfig(uint handle, ushort [] config);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teChargerGetStatus",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teChargerGetStatus(uint handle, out ushort status);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teNfcConfigure",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teNfcConfigure(uint handle, byte enable);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheInit",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheInit(uint handle, String configDb);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheInit",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheInit(uint handle, byte [] configDb);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheRead(uint handle, String file, ushort reserved);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheRead(uint handle, byte [] file, ushort reserved);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheReadItem",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheReadItem(uint handle, String key, StringBuilder value, out uint maxLen);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheReadItem",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheReadItem(uint handle, byte [] key, byte [] value, out uint maxLen);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheWriteItem",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheWriteItem(uint handle, String key, String value);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheWriteItem",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheWriteItem(uint handle, byte [] key, byte [] value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheWrite(uint handle, String file, ushort reserved);
        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teConfigCacheWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teConfigCacheWrite(uint handle, byte [] file, ushort reserved);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="teChipReset",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int teChipReset(uint handle, uint reserved);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePsRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePsRead(uint handle, uint keyId, ushort valueLen, ushort [] value, out ushort readLen);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePsWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePsWrite(uint handle, uint keyId, ushort valueLen, ushort [] value);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePsAudioRead",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePsAudioRead(uint handle, uint keyId, ushort valueLen, ushort [] value, out ushort readLen);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="tePsAudioWrite",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int tePsAudioWrite(uint handle, uint keyId, ushort valueLen, ushort [] value);


// DEPRECATED FUNCTIONS

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdPsuSmpsEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdPsuBuckReg(uint handle, ushort reg);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdPsuHvLinearEnable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdPsuMicEn(uint handle, ushort reg);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdLed0Enable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdLed0(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdLed1Enable",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdLed1(uint handle, ushort state);

        [DllImport(@".\QCC\TestEngine.dll", EntryPoint="bccmdChargerSuppressLed0",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int bccmdChargerSupressLed0(uint handle, ushort state);

    }
}
